import type { PortalState, PocStage, ScenarioCard } from "./types";

export const blankScenario: ScenarioCard = {
  id: "",
  name: "",
  department: "",
  businessOwner: "",
  users: "",
  frequency: "",
  trigger: "",
  input: "",
  currentProcess: "",
  currentOutput: "",
  duration: "",
  cost: "",
  baseline: "",
  aiTask: "",
  targetOutput: "",
  targetMetrics: "",
  humanBoundary: "",
  exclusions: "",
  dataSources: "",
  businessRules: "",
  sensitiveLevel: "",
  agentName: "",
  workflow: "",
  skills: "",
  tools: "",
  exceptionHandling: "",
  testRequirements: "",
  dimensions: "",
  threshold: "",
  failureTypes: "",
  acceptanceOwner: "",
  valueTarget: "",
  version: 0,
  status: "草稿",
};

export function createBlankStages(): PocStage[] {
  const definitions = [
    ["P0", "场景立项", "确认业务问题、价值假设与项目边界"],
    ["P1", "场景澄清", "完成场景卡并锁定人机协作边界"],
    ["P2", "评测准备", "建立测试集、评测维度和通过阈值"],
    ["P3", "技术验证", "完成多版本 Eval 并关闭严重失败"],
    ["P4", "业务试用", "业务用户试用并验证有效自动化率"],
    ["P5", "生产决策", "形成生产建议与最终验收结论"],
  ];
  return definitions.map(([code, name, objective], index) => ({
    id: crypto.randomUUID(),
    code,
    name,
    objective,
    status: index === 0 ? "进行中" : "未开始",
    owner: "待分配",
    dueDate: "待设置",
    criteriaTotal: 0,
    criteriaPassed: 0,
    evidenceCount: 0,
    blockers: [],
    criteria: [],
  }));
}

export const emptyState: PortalState = {
  workspace: {
    id: "",
    name: "尚未创建 Workspace",
    type: "团队空间",
    members: 0,
  },
  project: {
    id: "",
    name: "",
    type: "企业POC",
    organization: "",
    industry: "",
    goal: "",
    owner: "",
    businessOwner: "",
    stage: "",
    status: "",
    updatedAt: "",
  },
  scenario: blankScenario,
  stages: [],
  evalSuites: [],
  assets: [],
  risks: [],
  reviews: [],
  reports: [],
  activities: [],
  flow: {
    workspaceCreated: false,
    projectCreated: false,
    scenarioConfirmed: false,
    pocGenerated: false,
    evalCreated: false,
    assetRegistered: false,
    reviewSubmitted: false,
    reportGenerated: false,
  },
};
