import type { PortalState, PocStage, ScenarioCard } from "./types";

export const blankScenario: ScenarioCard = {
  id: "",
  name: "",
  department: "",
  businessOwner: "",
  users: "",
  frequency: "",
  trigger: "",
  input: "",
  currentProcess: "",
  currentOutput: "",
  duration: "",
  cost: "",
  baseline: "",
  aiTask: "",
  targetOutput: "",
  targetMetrics: "",
  humanBoundary: "",
  exclusions: "",
  dataSources: "",
  businessRules: "",
  sensitiveLevel: "",
  agentName: "",
  workflow: "",
  skills: "",
  tools: "",
  exceptionHandling: "",
  testRequirements: "",
  dimensions: "",
  threshold: "",
  failureTypes: "",
  acceptanceOwner: "",
  valueTarget: "",
  version: 0,
  status: "草稿",
};

export function createBlankStages(): PocStage[] {
  const definitions = [
    ["P0", "场景立项", "确认业务问题、价值假设与项目边界"],
    ["P1", "场景澄清", "完成场景卡并锁定人机协作边界"],
    ["P2", "评测准备", "建立测试集、评测维度和通过阈值"],
    ["P3", "技术验证", "完成多版本 Eval 并关闭严重失败"],
    ["P4", "业务试用", "业务用户试用并验证有效自动化率"],
    ["P5", "生产决策", "形成生产建议与最终验收结论"],
  ];
  return definitions.map(([code, name, objective], index) => ({
    id: crypto.randomUUID(),
    code,
    name,
    objective,
    status: index === 0 ? "进行中" : "未开始",
    owner: "待分配",
    dueDate: "待设置",
    criteriaTotal: 0,
    criteriaPassed: 0,
    evidenceCount: 0,
    blockers: [],
    criteria: [],
  }));
}

export const emptyState: PortalState = {
  diagnoses: [],
  workspace: {
    id: "00000000-0000-4000-8000-000000000001",
    name: "FDE Portal",
    type: "团队空间",
    members: 1,
  },
  project: {
    id: "",
    name: "",
    type: "企业POC",
    organization: "",
    industry: "",
    goal: "",
    owner: "",
    businessOwner: "",
    stage: "",
    status: "",
    updatedAt: "",
  },
  outcomeContract: {
    sponsor: "",
    metricName: "",
    baselineValue: "",
    targetValue: "",
    unit: "",
    annualValue: 0,
    annualCost: 0,
    valueFormula: "",
    successCondition: "",
    stopCondition: "",
    riskLevel: "中",
    status: "草稿",
  },
  stakeholders: [],
  workflowSteps: [],
  hypotheses: [],
  adoptionPlan: {
    champion: "",
    targetUsers: 0,
    activeUsers: 0,
    items: [
      {
        id: "adoption-sponsor",
        title: "Sponsor 已建立业务共识",
        owner: "业务负责人",
        completed: false,
      },
      {
        id: "adoption-champion",
        title: "Champion 用户参与共同设计",
        owner: "项目负责人",
        completed: false,
      },
      {
        id: "adoption-sop",
        title: "SOP 与人机责任边界已更新",
        owner: "业务负责人",
        completed: false,
      },
      {
        id: "adoption-training",
        title: "目标用户培训与 UAT 已完成",
        owner: "FDE",
        completed: false,
      },
      {
        id: "adoption-kpi",
        title: "KPI 与激励机制已对齐",
        owner: "Sponsor",
        completed: false,
      },
      {
        id: "adoption-feedback",
        title: "反馈与持续强化机制已运行",
        owner: "Champion",
        completed: false,
      },
    ],
  },
  productionProfile: {
    automationLevel: "AI建议",
    availabilityTarget: "99.5%",
    taskCostBudget: 0,
    rollbackOwner: "",
    items: [
      {
        id: "prod-data",
        title: "数据管道与权限校验通过",
        owner: "FDE",
        completed: false,
      },
      {
        id: "prod-regression",
        title: "Eval 回归集达到发布阈值",
        owner: "FDE",
        completed: false,
      },
      {
        id: "prod-monitor",
        title: "SLO、Trace 与成本告警已配置",
        owner: "系统 Owner",
        completed: false,
      },
      {
        id: "prod-human",
        title: "人工升级与接管机制已演练",
        owner: "业务负责人",
        completed: false,
      },
      {
        id: "prod-security",
        title: "安全、隐私与审计检查通过",
        owner: "安全负责人",
        completed: false,
      },
      {
        id: "prod-rollback",
        title: "灰度、降级与回滚方案已演练",
        owner: "系统 Owner",
        completed: false,
      },
      {
        id: "prod-runbook",
        title: "值班责任人与运维手册已确认",
        owner: "系统 Owner",
        completed: false,
      },
      {
        id: "prod-transfer",
        title: "客户团队知识转移已完成",
        owner: "FDE",
        completed: false,
      },
    ],
  },
  scenario: blankScenario,
  stages: [],
  evalSuites: [],
  assets: [],
  risks: [],
  reviews: [],
  reports: [],
  activities: [],
  flow: {
    workspaceCreated: true,
    projectCreated: false,
    scenarioConfirmed: false,
    pocGenerated: false,
    evalCreated: false,
    assetRegistered: false,
    reviewSubmitted: false,
    reportGenerated: false,
  },
};
